#!/bin/bash

echo "🚀 GUIA COMPLETO - Como executar o MirrorFit"
echo "============================================="

echo ""
echo "📋 PASSO 1: Preparar o ambiente"
echo "--------------------------------"
echo "1. Instale o Python 3.8+ no seu computador"
echo "2. Instale o Node.js (para servidor local do frontend)"
echo "3. Crie uma pasta para o projeto:"
echo "   mkdir mirrorfit-project"
echo "   cd mirrorfit-project"

echo ""
echo "📁 PASSO 2: Organizar arquivos"
echo "------------------------------"
echo "Crie esta estrutura de pastas:"
echo ""
echo "mirrorfit-project/"
echo "├── frontend/"
echo "│   ├── index.html"
echo "│   ├── styles.css"
echo "│   └── script.js"
echo "└── backend/"
echo "    ├── manage.py"
echo "    ├── requirements.txt"
echo "    ├── mirrorfit/"
echo "    │   ├── __init__.py"
echo "    │   ├── settings.py"
echo "    │   ├── urls.py"
echo "    │   └── wsgi.py"
echo "    └── virtual_tryon/"
echo "        ├── __init__.py"
echo "        ├── models.py"
echo "        ├── views.py"
echo "        ├── serializers.py"
echo "        ├── urls.py"
echo "        └── ai_processor.py"

echo ""
echo "🐍 PASSO 3: Configurar Backend (Django)"
echo "---------------------------------------"
echo "cd backend"
echo "python -m venv venv"
echo ""
echo "# Ativar ambiente virtual:"
echo "# Windows:"
echo "venv\\Scripts\\activate"
echo "# Linux/Mac:"
echo "source venv/bin/activate"
echo ""
echo "# Instalar dependências:"
echo "pip install -r requirements.txt"
echo ""
echo "# Configurar banco de dados:"
echo "python manage.py makemigrations"
echo "python manage.py migrate"
echo ""
echo "# Executar servidor Django:"
echo "python manage.py runserver"

echo ""
echo "🌐 PASSO 4: Executar Frontend"
echo "-----------------------------"
echo "# Em outro terminal, vá para a pasta frontend:"
echo "cd frontend"
echo ""
echo "# Opção 1 - Python (mais simples):"
echo "python -m http.server 8080"
echo ""
echo "# Opção 2 - Node.js:"
echo "npx http-server -p 8080"
echo ""
echo "# Opção 3 - PHP:"
echo "php -S localhost:8080"

echo ""
echo "🔗 PASSO 5: Acessar o sistema"
echo "-----------------------------"
echo "1. Backend Django: http://localhost:8000"
echo "2. Frontend: http://localhost:8080"
echo "3. Abra o frontend no navegador para usar o MirrorFit!"

echo ""
echo "⚠️  POSSÍVEIS PROBLEMAS E SOLUÇÕES"
echo "=================================="
echo ""
echo "❌ Erro: 'pip não encontrado'"
echo "✅ Solução: Instale o Python corretamente"
echo ""
echo "❌ Erro: 'ModuleNotFoundError: No module named django'"
echo "✅ Solução: Ative o ambiente virtual e instale requirements.txt"
echo ""
echo "❌ Erro: 'Port already in use'"
echo "✅ Solução: Use outra porta: python manage.py runserver 8001"
echo ""
echo "❌ Erro: CORS (frontend não conecta com backend)"
echo "✅ Solução: Já configurado no settings.py"
echo ""
echo "❌ Erro: 'cv2 not found'"
echo "✅ Solução: pip install opencv-python"

echo ""
echo "🎯 COMANDOS RÁPIDOS"
echo "==================="
echo ""
echo "# Parar servidores:"
echo "Ctrl + C (em ambos os terminais)"
echo ""
echo "# Reinstalar dependências:"
echo "pip install -r requirements.txt --force-reinstall"
echo ""
echo "# Limpar banco de dados:"
echo "rm db.sqlite3"
echo "python manage.py migrate"
echo ""
echo "# Ver logs de erro:"
echo "python manage.py runserver --verbosity=2"

echo ""
echo "✅ PRONTO! Seu MirrorFit está rodando!"
